### ISSUE TITLE
¿Plataforma?

### ISSUE THREAD

**Issue by Bienen27** [Proyectos1-FDI-UCM/c2223-Grupo02#65]
### Descripción

No sé por qué hay una plataforma ahí sin sentido, casi al terminar el nivel. Hay dos problemas. El primero es de diseño, que no sé qué hace la plataforma ahí en medio, no cumple ninguna función; y segundo, la hitbox de debajo de la plataforma está muy mal hecha, te das en la cabeza mucho antes de llegar.

### Pasos 

Detallar los pasos seguidos para poder reproducir el error. Si no se ha podido reproducir, entonces indicarlo igualmente.

1.	Ir al nivel _LASERS_
2.	Ir a la plataforma del final.

### Captura de pantalla o vídeo

![](https://i.imgur.com/5rdVI1n.png)

**Comment by DenisaJuarranzBerindea** [comment]
No se trata de un bug. Estos niveles han sido diseñados para la prueba en base a los niveles originales. Por lo que, en el nivel original, en esa zona, hay enemigos, mientras que en el nivel de pruebas, no lo hay.
